NAME: 'NCL_with_contrastive'
OUTPUT_DIR: '/media/ssd1/lijun/output/NCL_with_contrastive'
SHOW_STEP: 100
SAVE_STEP: 100
VALID_STEP: 1
INPUT_SIZE: (32, 32)
COLOR_SPACE: 'RGB'

DATASET:
  DATASET: 'MULTI_NETWORK_CIFAR_MOCO_AUGPLIS'
  TRAIN_JSON: '/media/ssd1/lijun/imbalance_cifar/converted/cifar100_imbalance100/cifar100_imbalance100_train.json'
  VALID_JSON: '/media/ssd1/lijun/imbalance_cifar/converted/cifar100_imbalance100/cifar100_imbalance100_valid.json'

NETWORK:
  MA_MODEL_ALPHA: 0.999
  MOCO: True
  MOCO_K: 1024
  MOCO_T: 0.2
  MOCO_DIM: 64
BACKBONE:
  TYPE: 'res32_cifar'
  MULTI_NETWORK_TYPE: ['res32_cifar','res32_cifar','res32_cifar']
MODULE:
  TYPE: 'GAP'

DROPOUT: False

CLASSIFIER:
  TYPE: 'FC'
  SEMI_TYPE: 'mlp'
  BIAS: True

LOSS:
  LOSS_TYPE: 'NIL_NBOD'
  MULTI_CLASIIFIER_LOSS:
    DIVERSITY_FACTOR: 0.6
    DIVERSITY_FACTOR_HCM: 0.6
  HCM_N: 30
  HCM_RATIO: 1.0
  CE_RATIO: 1.0
  CON_RATIO: 1.0
TRAIN:

  BATCH_SIZE: 64
  MAX_EPOCH: 400
  NUM_WORKERS: 8
  COMBINER:
    TYPE: 'multi_network_default_CON'
  OPTIMIZER:
    TYPE: 'SGD'
    BASE_LR: 0.1
    MOMENTUM: 0.9
    WEIGHT_DECAY: 2e-4
  LR_SCHEDULER:
    TYPE: 'warmup'
    LR_STEP: [320,360]
    LR_FACTOR: 0.1
    WARM_EPOCH: 5
  TENSORBOARD:
    ENABLE: True
  SAMPLER:
    TYPE: 'default'
    MULTI_NETWORK_TYPE: ['default']

  DISTRIBUTED: False
  SYNCBN: True

TRANSFORMS:
  TRAIN_TRANSFORMS: ('random_crop', 'random_horizontal_flip')
  TEST_TRANSFORMS: ()

TEST:
  BATCH_SIZE: 256
  NUM_WORKERS: 8
  MODEL_FILE: 'best_model.pth'