NAME: 'NCL'
OUTPUT_DIR: '/media/ssd1/lijun/output/NCL'
SHOW_STEP: 200
SAVE_STEP: 10
VALID_STEP: 1
INPUT_SIZE: (224, 224)
COLOR_SPACE: 'RGB'

DATASET:
  DATASET: 'Places_LT_MOCO'
  TRAIN_JSON: '/home/lijun/papers/NCL/dataset_json/Places_LT_train.json'
  VALID_JSON: '/home/lijun/papers/NCL/dataset_json/Places_LT_val.json'

NETWORK:
  MA_MODEL_ALPHA: 0.999
  MOCO: True
  MOCO_K: 65536
  MOCO_T: 0.2
  MOCO_DIM: 1024
BACKBONE:
  TYPE: 'res152'
  MULTI_NETWORK_TYPE: ['res152','res152','res152']
  PRETRAINED_MODEL: '/home/lijun/papers/NCL/lib/backbone/resnet152-b121ed2d.pth'
MODULE:
  TYPE: 'GAP'

DROPOUT: False

CLASSIFIER:
  TYPE: 'cos'
  SEMI_TYPE: 'mlp'
  BIAS: True

LOSS:
  LOSS_TYPE: 'NIL_NBOD'
  MULTI_CLASIIFIER_LOSS:
    DIVERSITY_FACTOR: 0.6
    DIVERSITY_FACTOR_HCM: 0.6
  HCM_N: 122
  HCM_RATIO: 1.0
  CE_RATIO: 1.0
  CON_RATIO: 1.0
TRAIN:

  BATCH_SIZE: 32
  MAX_EPOCH: 30
  NUM_WORKERS: 8
  COMBINER:
    TYPE: 'multi_network_default_CON'
  OPTIMIZER:
    TYPE: 'SGD'
    BASE_LR: 0.02
    MOMENTUM: 0.9
    WEIGHT_DECAY: 2e-4
  LR_SCHEDULER:
    TYPE: 'warmup'
    LR_STEP: [10,20]
    LR_FACTOR: 0.1
    WARM_EPOCH: 5
  TENSORBOARD:
    ENABLE: False
  SAMPLER:
    TYPE: 'default'
    MULTI_NETWORK_TYPE: ['default']

  DISTRIBUTED: True
  SYNCBN: True

TRANSFORMS:
  TRAIN_TRANSFORMS: ("random_resized_crop", "random_horizontal_flip", "color_jitter")
  TEST_TRANSFORMS: ("shorter_resize_for_crop", "center_crop")

TEST:
  BATCH_SIZE: 64
  NUM_WORKERS: 8
  MODEL_FILE: 'best_model.pth'